[package]
name    = "anyrun-pass"
version = "25.12.0"
edition = "2021"

[lib]
crate-type = [ "cdylib" ]

[dependencies]
anyrun-plugin = { git = "https://github.com/Kirottu/anyrun" }
abi_stable = "0.11.1"
glob = "0.3.3"
nucleo-matcher = "0.3.1"
serde = "*"
ron = "0.8.0"
sequoia-openpgp = "2.1.0"